### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by mcswains** [kayabaNerve/tip-bot#10]
I'm receiving this message when i try to run node main.js

SyntaxError: C:\Users\USER\Desktop\BOT\settings.json: Unexpected token U in JSON at position 378
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:801:27)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at main (C:\Users\USER\Desktop\BOT\main.js:92:24)
    at C:\Users\USER\Desktop\BOT\main.js:129:15
    at Object.<anonymous> (C:\Users\USER\Desktop\BOT\main.js:134:3)
    at Module._compile (internal/modules/cjs/loader.js:776:30)

I'm sorry if this is user error, but what do I do?

**Comment by sdkayy** [comment]
Did you happen to rename the btcSettings.json to just settings.json and then edit it?

**Comment by kayabaNerve** [comment]
It's a typo in your config.
