### ISSUE TITLE
When I run "node main.js" I get error.

### ISSUE THREAD

**Issue by TrueUW** [kayabaNerve/tip-bot#11]
When I run node main.js I get this error:

> SyntaxError: /home/discordtip/tip-bot/settings.json: Unexpected string in JSON at position 746
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:797:27)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at main (/home/discordtip/tip-bot/main.js:92:24)
    at /home/discordtip/tip-bot/main.js:129:15
    at Object.<anonymous> (/home/discordtip/tip-bot/main.js:134:3)

**Comment by kayabaNerve** [comment]
This means you wrote an invalid config.
